export const LOAD_REVIEWS = "LOAD_REVIEWS";

export const LOAD_REVIEWS_START = "LOAD_REVIEWS_START";

export const LOAD_REVIEWS_SUCCESS = "LOAD_REVIEWS_SUCCESS";

export const LOAD_REVIEWS_FAIL = "LOAD_REVIEWS_FAIL";
